using BaseTest.Fixtures;
using QueryTest.Interfaces;
using QueryTest.Utils;
using SharpOrm;
using SharpOrm.Builder;
using SharpOrm.Fb;
using Xunit.Abstractions;

namespace QueryTest.Firebird
{
    public class TableBuilderTest(ITestOutputHelper output, MockFixture<FbQueryConfig> connection) : DbGrammarTestBase(output, connection), IClassFixture<MockFixture<FbQueryConfig>>, ITableBuilderTest
    {
        [Fact]
        public void ExistsTableTest()
        {
            var grammar = GetTableGrammar(new TableSchema("MyTable"));
            var expected = new SqlExpression("SELECT COUNT(*) FROM RDB$RELATIONS R WHERE R.RDB$RELATION_TYPE IN (0, 2, 3) AND R.RDB$RELATION_NAME = UPPER(?)", "MyTable");

            Assert.Equal(expected, grammar.Exists());
        }

        [Fact]
        public void ExistsTempTableTest()
        {
            var grammar = GetTableGrammar(new TableSchema("MyTable") { Temporary = true });
            var expected = new SqlExpression("SELECT COUNT(*) FROM RDB$RELATIONS R WHERE R.RDB$RELATION_TYPE IN (4,5) AND R.RDB$RELATION_NAME = UPPER(?)", "MyTable");
            var current = grammar.Exists();

            Assert.Equal(expected, current);
        }

        [Fact]
        public void DropTableTest()
        {
            var grammar = GetTableGrammar(new TableSchema("MyTable"));
            var expected = new SqlExpression("DROP TABLE \"MyTable\"");
            var current = grammar.Drop();

            Assert.Equal(expected, current);
        }

        [Fact]
        public void DropTempTableTest()
        {
            var grammar = GetTableGrammar(new TableSchema("MyTable") { Temporary = true });
            var expected = new SqlExpression("DROP TABLE \"MyTable\"");
            var current = grammar.Drop();

            Assert.Equal(expected, current);
        }

        [Fact]
        public void CreateBasedTable()
        {
            var q = Query.ReadOnly("BaseTable", Config).Select("Id", "Name");
            q.Where("Id", ">", 50);

            var grammar = GetTableGrammar(new TableSchema("MyTable", q));
            var expected = new SqlExpression("CREATE TABLE \"MyTable\" AS SELECT \"Id\", \"Name\" FROM \"BaseTable\" WHERE \"Id\" > 50");

            Assert.Equal(expected, grammar.Create());
        }

        [Fact]
        public void CreateBasedTempTable()
        {
            var q = Query.ReadOnly("BaseTable", Config).Select("Id", "Name");
            q.Where("Id", ">", 50);

            var grammar = GetTableGrammar(new TableSchema("MyTable", q) { Temporary = true });
            var expected = new SqlExpression("CREATE GLOBAL TEMPORARY TABLE \"MyTable\" AS SELECT \"Id\", \"Name\" FROM \"BaseTable\" WHERE \"Id\" > 50");

            Assert.Equal(expected, grammar.Create());
        }

        [Fact]
        public void CreateTable()
        {
            var cols = new TableColumnCollection();
            cols.AddPk("Id").AutoIncrement = true;
            cols.Add<string>("Name");
            cols.Add<int>("Status").Unique = true;
            cols.Add<int>("Status2").Unique = true;

            var grammar = GetTableGrammar(new TableSchema("MyTable", cols));
            var expected = new SqlExpression("CREATE TABLE \"MyTable\" (\"Id\" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\"Name\" VARCHAR(255) NULL,\"Status\" INTEGER NULL,\"Status2\" INTEGER NULL,CONSTRAINT \"UC_MyTable\" UNIQUE (\"Status\",\"Status2\"),CONSTRAINT \"PK_MyTable\" PRIMARY KEY (\"Id\"))");

            Assert.Equal(expected, grammar.Create());
        }

        [Fact]
        public void CreateTableMultiplePk()
        {
            var cols = new TableColumnCollection();
            cols.AddPk("Id").AutoIncrement = true;
            cols.AddPk("Id2");

            var grammar = GetTableGrammar(new TableSchema("MyTable", cols));
            var expected = new SqlExpression("CREATE TABLE \"MyTable\" (\"Id\" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\"Id2\" INTEGER NOT NULL,CONSTRAINT \"PK_MyTable\" PRIMARY KEY (\"Id\",\"Id2\"))");

            Assert.Equal(expected, grammar.Create());
        }
    }
}
